name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Release binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3

      - name: Build
        run: |
          GOOS=linux  GOARCH=amd64 go build -o bin/dobato-linux-amd64.${{ github.ref }}
          GOOS=darwin GOARCH=amd64 go build -o bin/dobato-darwin-amd64.${{ github.ref }}
          GOOS=darwin GOARCH=arm64 go build -o bin/dobato-darwin-arm64.${{ github.ref }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@2.1.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/dobato-*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
